test: movementtest.cpp ../arduino_dalek_receiver/Movement.cpp ../arduino_dalek_receiver/Movement.h
	g++ -D_UNIX -I../arduino_dalek_receiver ../arduino_dalek_receiver/Movement.cpp movementtest.cpp -o mt && \
	./mt
